name: Continuous Integration

on:
  pull_request:
    branches: [ main ]

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Install dependencies in the root
        run: npm ci
      - name: Runs linter
        run: npm run lint
  front_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Install dependencies in the root
        run: npm ci
      - name: Install dependencies in the client folder
        run: npm ci
        working-directory: ./src/client
      - name: Run front end tests
        run: npm test
        working-directory: ./src/client
  back_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Install dependencies in the root
        run: npm ci
      - name: Docker compose
        run: docker-compose up -d
      - name: Install dependencies in the server folder
        run: npm ci
        working-directory: ./src/server
      - name: Database init
        run: psql postgres://postgres:example@localhost:5432/postgres -f ./src/server/migrations/1_create_initial_tables.sql
      - name: Run back end tests
        run: npm test
        working-directory: ./src/server